os: osx
osx_image: xcode10

before_install:
  - brew update
addons:
  homebrew:
    packages:
      - go
      - gradle
      - grpc
      - mono
      - nuget
      - pkg-config
      - protobuf
      - rust
    casks:
      - dotnet-sdk
install:
  - brew upgrade protobuf

before_cache:
  - brew cleanup
  - find /usr/local/Homebrew \! -regex ".+\.git.+" -delete
cache:
  directories:
    - ${HOME}/Library/Caches/Homebrew
    - /usr/local/Homebrew

env:
  - PATH="${PATH}:/usr/local/opt/gettext/bin:${HOME}/go/bin:${HOME}/.cargo/bin"
script:
  - gradle buildAll

branches:
  only:
    - master
