os: osx
osx_image: xcode10

addons:
  homebrew:
    update: true
    taps:
      - figroc/homebrew-versions
    packages:
      - go
      - gradle
      - grpc
      - mono
      - nuget
      - pkg-config
      - protobuf@3.12.2
      - rust
    casks:
      - dotnet-sdk

before_cache:
  - brew cleanup
  - find /usr/local/Homebrew \! -regex ".+\.git.+" -delete
cache:
  directories:
    - ${HOME}/Library/Caches/Homebrew
    - /usr/local/Homebrew

env:
  global:
    - PATH="${PATH}:/usr/local/opt/gettext/bin:${HOME}/go/bin:${HOME}/.cargo/bin"
    - GO111MODULE=on
script:
  - gradle buildAll

branches:
  only:
    - master
