os: osx
osx_image: xcode10

addons:
  homebrew:
    update: true
    packages:
      - go
      - gradle
      - grpc
      - mono
      - nuget
      - pkg-config
      - rust
    casks:
      - dotnet-sdk

before_install:
  - |
    cd $(brew --repository)/Library/Taps/homebrew/homebrew-core
    git checkout f13bf9adadfe0525c2f4aaeb18b21c636bd7ce1a
    brew install protobuf
    git checkout master

before_cache:
  - brew cleanup
  - find /usr/local/Homebrew \! -regex ".+\.git.+" -delete
cache:
  directories:
    - ${HOME}/Library/Caches/Homebrew
    - /usr/local/Homebrew

env:
  global:
    - PATH="${PATH}:/usr/local/opt/gettext/bin:${HOME}/go/bin:${HOME}/.cargo/bin"
    - GO111MODULE=on
script:
  - gradle buildAll

branches:
  only:
    - master
