os: osx
osx_image: xcode10

addons:
  homebrew:
    update: true
    packages:
      - go
      - gradle
      - grpc
      - mono
      - nuget
      - pkg-config
      - protobuf
      - rust
    casks:
      - dotnet-sdk
install:
  - | # protobuf@3.12.2
      git -C $(brew --repo homebrew/core) checkout f13bf9adadfe0525c2f4aaeb18b21c636bd7ce1a
      brew unlink protobuf && HOMEBREW_NO_AUTO_UPDATE=1 brew install protobuf
      git -C $(brew --repo homebrew/core) checkout master

before_cache:
  - brew cleanup
  - find /usr/local/Homebrew \! -regex ".+\.git.+" -delete
cache:
  directories:
    - ${HOME}/Library/Caches/Homebrew
    - /usr/local/Homebrew

env:
  global:
    - PATH="${PATH}:/usr/local/opt/gettext/bin:${HOME}/go/bin:${HOME}/.cargo/bin"
    - GO111MODULE=on
script:
  - gradle buildAll

branches:
  only:
    - master
