os: osx
osx_image: xcode10
addons:
  homebrew:
    packages:
      - go
      - gradle
      - grpc
      - mono
      - nuget
      - protobuf
      - rust
    casks:
      - dotnet-sdk
env:
  - PATH="${PATH}:${HOME}/.go/bin:${HOME}/.cargo/bin"
script:
  - gradle buildAll
