os: osx
osx_image: xcode10

addons:
  homebrew:
    update: true
    packages:
      - go
      - gradle
      - grpc
      - mono
      - nuget
      - pkg-config
      - protobuf
      - rust
    casks:
      - dotnet-sdk

before_cache:
  - brew cleanup
  - find /usr/local/Homebrew \! -regex ".+\.git.+" -delete
cache:
  directories:
    - ${HOME}/Library/Caches/Homebrew
    - /usr/local/Homebrew

env:
  global:
    - CPPFLAGS="-I/usr/local/opt/openssl@1.1/include ${CPPFLAGS}"
    - LDFLAGS="-L/usr/local/opt/openssl@1.1/lib ${LDFLAGS}"
    - PATH="${PATH}:/usr/local/opt/gettext/bin:${HOME}/go/bin:${HOME}/.cargo/bin"
    - PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig:${PKG_CONFIG_PATH}"
    - GO111MODULE=on
script:
  - gradle buildAll

branches:
  only:
    - master
