os: osx
osx_image: xcode10
addons:
  homebrew:
    packages:
      - go
      - gradle
      - grpc
      - mono
      - nuget
      - protobuf
      - rust
    casks:
      - dotnet-sdk
env:
  - PATH="${PATH}:/usr/local/opt/gettext/bin:${HOME}/go/bin:${HOME}/.cargo/bin"
script:
  - echo ${CARGO_HOME}
  - gradle buildAll
branches:
  only:
    - master
