on: [pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - docker run --rm --user $(id -u):$(id -g)
        -v ${{ github.workspace }}:/work
        figroc/tfsclient:build
        gradle --no-daemon buildAll
