on: [pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        with:
          image: figroc/tfsclient:build
          options: -v ${{ github.workspace }}:/work
          run: gradle --no-daemon buildAll
